### PR TITLE
Display likes on homepage

### PR DESCRIPTION
**Pull request by JonahKayizzi**
This pull request consists of the following changes;

- Fetched likes for each pokemon from the Involvement API
- Displayed likes for each pokemon on the home page

### CODE REVIEW

**Review by d4nQw3rty — CHANGES_REQUESTED** [review]
Excellent @JonahKayizzi always a clean and easy-to-follow code :+1: 
But I have some issues about functionality that may interest you to know to improve the code. :hammer_and_wrench:  

When I check the response of the function to get items like I got this 
image

- There are two items with names item1 and item2,

- There are two items with almost the same name if you compare with == '892' and 892;

- You may want to check the data structure to keep it equal in all elements of the same kind.

- What do you think about changing the style for the heart in the likes? it would be better if only change it when you click it and not when you make a mouseover. We can save this status in the local storage to check if the user already clicks it. :smile:
- 
-And if we compare the response of the API there are two elements that are not displaying their likes.
image

**Comment by JonahKayizzi** [comment]
Thank you @d4nQw3rty  for the review.
- I will change the behaviour of the like icons like you have suggested. I plan to do this from the branch [create-feature-add-new-like](https://github.com/JonahKayizzi/Javascript-Capstone-Pokemon-API/tree/create-feature-add-new-like) for adding likes.
- The `item_id`s `"item1"`, `"item2"` & `892` were added while I was testing the API end points. Please ignore then since we do not plan to use them
- The last two items do not display the number of likes because I have intentionally not given likes to them for purposes of testing the POST like end point when working on this branch  [create-feature-add-new-like](https://github.com/JonahKayizzi/Javascript-Capstone-Pokemon-API/tree/create-feature-add-new-like)

**Comment by d4nQw3rty** [comment]
Congratulation @JonahKayizzi, there is nothing more to say than Merge it.

**Review by d4nQw3rty — APPROVED** [review]
Great Job! :+1: 
Now you can merge the repository to move forward in the project.

**Pull request merged**
